### ISSUE TITLE
exception when sampling: Cannot cast Hashmap.TreeNode ...

### ISSUE THREAD

**Issue by samthiriot** [samthiriot/knime.bayesiannetworks#39]
Related to a threading issue
https://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode/29971168

yet everything is supposed to be threadsafe... to be checked

**Comment by samthiriot** [comment]
not fixed yet
maybe encapsulate computation of probabilities and sampling functions so we trace it back

**Comment by samthiriot** [comment]
got the pb for method round_random
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.resear.thiriot.knime.bayesiannetworks.sample.SampleFromBNNodeModel.execute(SampleFromBNNodeModel.java:415)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:576)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1236)
	at org.knime.core.node.Node.execute(Node.java:1016)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:558)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:334)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1835)
	at java.util.HashMap$TreeNode.treeify(HashMap.java:1951)
	at java.util.HashMap.treeifyBin(HashMap.java:772)
	at java.util.HashMap.putVal(HashMap.java:644)
	at java.util.HashMap.put(HashMap.java:612)
	at ch.resear.thiriot.knime.bayesiannetworks.DataTableToBNMapper.createCellForStringValue(DataTableToBNMapper.java:123)
	at ch.resear.thiriot.knime.bayesiannetworks.sample.SampleFromBNNodeModel$BNToTableSampler.call(SampleFromBNNodeModel.java:268)
	at ch.resear.thiriot.knime.bayesiannetworks.sample.SampleFromBNNodeModel$BNToTableSampler.call(SampleFromBNNodeModel.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
